### PR TITLE
Fix subtraction

### LINKED ISSUE #3: Subtraction Fix
Fix Subtraction Error and added testing

### PR DESCRIPTION
**Pull request by Priya-Nigam**
Fixed Subtraction Error and Added Testing to Demonstrate that Subtraction now works.

### CODE REVIEW

File: calculator/src/main/java/edu/temple/cis3296/CalculatorModel.java [hunk 1]
```diff
@@ -106,8 +106,9 @@ public double operationAdd(double rhs, double lhs) {
         return lhs + lhs;
     }
 
+    //Fixed bug by changing equation from lhs-rhs to rhs-lhs
     public double operationSubst(double rhs, double lhs) {
-        return (lhs - rhs);
+        return (rhs-lhs);
```
Comment (tug59430) [inline calculator/src/main/java/edu/temple/cis3296/CalculatorModel.java:111]: Subtraction looks good!

**Review by tug59430 — APPROVED** [review]
Subtraction method fix and subtraction unit tests look good.
